jetson_1:
  ros_parameters:
    camera_type: 'blackfly_s'
    serial: "'21502646'"
    sonar: 'false'
    cam_topic: '/debayer/image_raw/compressed'
    namespace: 'jetson_1'
    frequency: '30.0'

jetson_2:
  ros_parameters:
    camera_type: 'blackfly_s'
    serial: "'21387972'"
    sonar: 'true'
    cam_topic: '/debayer/image_raw/compressed'
    namespace: 'jetson_2'
    frequency: '30.0'
